apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-minor-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-minor-1
  template:
    metadata:
      labels:
        app: mlops-minor-1
    spec:
      containers:
      - name: mlops-minor-1
        image: us-central1-docker.pkg.dev/melodic-nature-455323-u8/mlops-minor-1/mlops-minor-1:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: mlops-minor-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
